---
title: "OASIS report"
author: "Antonios Lioutas"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
```


### Oligopaints library appended sequences overview

### Reagents to Order

#### 1. Oligopaints Library
* We typically order the library (file: final_LAD_oligopaints_ROI1_appended_oligopaints_order_v1.txt) from Twist (www.twistbioscience.com)

#### 2. Oligopaints library amplification primers (5' to 3')
Amplification primers are usually ordered from IDT.

#### 3. Bridge oligos
Bridge oligos will bind to the complementary streets (bs1) on the primary Oligopaints library after FISH. Based on the design of this library you will be using 3 different fluorophores to image 3 genomic regions 


#### 4. Secondary oligos (with fluorophore of your choice)
Secondary oligos will bind to the complementary bridges.

* sec1 : [5' Fluorophore] - CACACGCTCTTCCGTTCTATGCGACGTCGGTG - [3' Fluorophore]
* sec5 : [5' Fluorophore] - ACACCCTTGCACGTCGTGGACCTCCTGCGCT - [3' Fluorophore]
* sec6 : [5' Fluorophore] - TGATCGACCACGGCCAAGACGGAGAGCGTGTG - [3' Fluorophore]


#### 5. Toeing Imaging oligos
Toeing oligos will remove the bridge (together with the secondary). This is an efficient way to perform sequential imaging (walking along chromosomes as described in Nir, Farabella, Perez Estrada, Ebeling,  et. al. PLOS Genetics, , 2018).

#### 6. OligoFISSEQ Imaging oligos
OligoFISSEQ (Nguyen, Chattoraj, Castillo, et. al., Nat Methods, 2020) is a multiplexing imaging technology. You will not be using these barcodes (ms1) for now but they are there for future imaging multiplexing.

* OligoFISSEQ sequencing Primer: /5Phos/GTCAATCGTCCGGGACGT
* JEB Alexa647 8mer: /5Alex647N//ideoxyI//ideoxyI//i3Thio-dI/*GAGCG
* JEB Alexa488 8mer: /5Alex488N//ideoxyI//ideoxyI//i3Thio-dI/*AGACC
* JEB TexaRed 8mer: /5TexRd-XN//ideoxyI//ideoxyI//i3Thio-dI/*TGACT
* JEB Cy3 8mer: /5Cy3/dIdI/3-thio-dI/*GACCA